[book]
authors = ["kurteklund"]
language = "en"
multilingual = false
src = "src"
title = "Kurt/Stefan - Nordisk Standard"

[build]
build-dir = "docs" 

[output.html]
additional-css = ["bridge.css"]

[preprocessor.example]
command = "/home/kurt/github/mdbook-bridge-preprocessor/mdbook-bridge-preprocessor"
renderer = ["html"] 
